default: &default

  # Basic
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  census_url: <%= ENV['CENSUS_URL'] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

  # Omniauth
  omniauth:
    facebook:
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>

  # Geocoding
  geocoder:
    here_app_id: <%= ENV["GEOCODER_LOOKUP_APP_ID"] %>
    here_app_code: <%= ENV["GEOCODER_LOOKUP_APP_CODE"] %>

  # SMTP
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  mailer_sender: <%= ENV["MAILER_SENDER"] %>

  # UNED
  uned:
    sso_wsdl_url: <%= ENV["UNED_SSO_WSDL_URL"] %>
    sso_app_id: <%= ENV["UNED_SSO_APP_ID"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
